apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # Απαραίτητο για StatefulSet ώστε να διατηρείται σταθερό DNS
  selector:
    app: mysql
